version: 2
jobs:
  build-api:  
    docker:
      - image: microsoft/dotnet:2.1-sdk
    steps:
      - checkout
      - run: find .
      - run: dotnet build src
      - run: dotnet test arc/BasketApi.Tests
workflows:
  version: 2
  api:
    jobs:
      - build-api